describe("Part 8: Contact Form", () => {
  beforeEach(() => {
    cy.visit("/");
  });

  it("Test Case 9: Submit Contact Us Form", () => {
    // Click Contact Us
    cy.get('.shop-menu a[href="/contact_us"]').click();

    // Enter name, email, subject, and message
    cy.get('[data-qa="name"]').type("Jane Doe");
    cy.get('[data-qa="email"]').type("jane_doe@test.com");
    cy.get('[data-qa="subject"]').type("Automation Test Run");
    cy.get('[data-qa="message"]').type("This is an automated assertion message generated by Cypress script.");

    // Upload a file using native selectFile handling
    cy.get('input[name="upload_file"]').selectFile({
      contents: Cypress.Buffer.from("Mock Attachment File Data"),
      fileName: "test_report.txt",
      mimeType: "text/plain"
    });

    // Handle the window confirmation alert interceptor (clicks "OK" automatically)
    cy.on("window:confirm", (text) => {
      expect(text).to.contains("Press OK to proceed");
      return true;
    });

    // Click Submit
    cy.get('[data-qa="submit-button"]').click();

    // Verify success message is displayed
    cy.get(".status.alert.alert-success").should("be.visible")
      .and("contain.text", "Success! Your details have been submitted successfully.");
  });
});
